package by.dzimash.model

import java.math.BigDecimal
import java.util.UUID

enum class SignalType {
    BUY,
    SELL,
}

/**
 * Represents a trading signal generated by a strategy.
 * This is the event that will trigger the ExecutionHandler later.
 *
 * @param symbol The trading pair, e.g., "SHIBUSDT".
 * @param signalType The action to take (BUY or SELL).
 * @param price The price at which the signal was generated.
 * @param id A unique identifier for this signal.
 */
data class Signal(
    val symbol: String,
    val signalType: SignalType,
    val price: BigDecimal,
    val id: UUID = UUID.randomUUID()
)
