bot {
  # A list of all strategies the bot should attempt to run.
  strategies = [
    {
      enabled = true
      symbol = "SHIBUSDT"
      type = "range"
      parameters = {
        lower-bound = "0.00002400"
        upper-bound = "0.00002550"
      }
    },
    {
      enabled = true
      symbol = "DOGEUSDT"
      type = "range"
      parameters = {
        lower-bound = "0.15"
        upper-bound = "0.17"
      }
    },
    {
      enabled = false
      symbol = "BTCUSDT"
      type = "range"
      parameters = {
        lower-bound = "68000"
        upper-bound = "70000"
      }
    }
  ]
  
  # A list of all data handlers the bot can use.
  data-handlers = [
    {
      enabled = true
      type = "binance"
      parameters = {
        base-url = "wss://stream.binance.com:9443/ws"
      }
    }
  ]
}