package by.dzimash.engine

import by.dzimash.handler.DataHandler
import by.dzimash.model.Signal
import by.dzimash.strategy.TradingStrategy
import kotlinx.coroutines.flow.Flow

/**
 * The StrategyEngine connects a DataHandler to a TradingStrategy.
 * It orchestrates the flow of data from the market to the strategy's brain.
 */
class StrategyEngine(
    private val dataHandler: DataHandler,
    private val strategy: TradingStrategy
) {
    /**
     * Starts the engine for a specific symbol.
     * It fetches the price ticks from the data handler and pipes them
     * into the strategy for evaluation.
     *
     * @param symbol The trading pair to run the engine for.
     * @return A flow of trading signals generated by the strategy.
     */
    fun start(symbol: String): Flow<Signal> {
        val priceTicks = dataHandler.listenToPriceTicks(symbol)
        return strategy.evaluate(priceTicks)
    }
}